### ISSUE TITLE
Remove disqordia.space

### ISSUE THREAD

**Issue by M-i-k-o-t-o** [pixeldesu/fediverse-friendly-moderation-covenant#8]
The admin defederates remote users instance-wide and harasses them due to personal disagreements and without any prior "communication before actions".

This breaks "Actions taken will respond to the bare minimum to keep the network operating and not influence the ability of the instances users to connect to other people" and "Communication before Actions".

It also came to my attention that they defederated with various instances without any previous communication.

Also relevant: https://neckbeard.xyz/notice/A8jdOuZlygrcMPahm4 and https://neckbeard.xyz/notice/A8l6jIdvIae6chZAhM

**Comment by pixeldesu** [comment]
> Regardless of all given points above, in special cases the instance moderation/administration might still opt to block an instance, while this is tried to be avoided at most.

Just copy-pasting from the other issue here: 

> First of all, I'm not a governing instance nor authority on who follows the self-imposed rules or not.
> 
> It's specifically written to be left open too, because of cases like this, and when the moderation team of an instance decides to defederate/block an instance to keep its own users safe, then so be it.

Also, looking at the communication from the moderation team, the defederation was requested from the instances own users, the moderation acknowledged not the entire instance is bad, but they had to weigh the situation out. I think it's commendable open communication about that issue here, and once again, if the instance decides to do so, that's on them.

**Comment by M-i-k-o-t-o** [comment]
Fair enough, I take "Who's using the Covenant?" to simply mean "who claims to be using the covenant in their about page" then.

(I see no mention of the covenant in disqordia.space by the way, so I do wonder how you decided to add it)

> It's specifically written to be left open too, because of cases like this

So it is designed to be as useless as possible, is there any point to signing this other than virtue signaling then? If it is not even attempted to be followed then there is no point to it.

> when the moderation team of an instance decides to defederate/block an instance to keep its own users safe

Said defederations were not placed to keep their own users safe.

> the defederation was requested from the instances own users

This might be true for the defederation of kf/poast from disqordia (not for FAB though) but not for the defederation of the other instances or remote users.

Regardless though the same could be said for the instances that this covenant is a reaction to. I do not think that types.pl users would like to federate with disqordia or FAB either.

Considering that, I take it to simply mean "we are not like them! (except when we are)" and appear as victims in a grand defederation scheme by "woke" people while doing the same.

**Comment by pixeldesu** [comment]
> Fair enough, I take "Who's using the Covenant?" to simply mean "who claims to be using the covenant in their about page" then.

Pretty much, yes.

> (I see no mention of the covenant in disqordia.space by the way, so I do wonder how you decided to add it)

I checked, and they don't fully copy-pasted it into their /about page but the repository is linked at the very end of the description.

> > It's specifically written to be left open too, because of cases like this
>
> So it is designed to be as useless as possible, is there any point to signing this other than virtue signaling then? If it is not even attempted to be followed then there is no point to it.

_"If it is not even attempted to be followed then there is no point to it."_ That's true.

Since this is an open document anyone could just _pledge_ to it without having the necessary backlink up, whatsoever, or since signing having changed their stance on it, who knows. I'm not keeping tabs on the instances after all.

It pretty much is just made to be something that's expected to be handled in good faith, but with moderation it itself being a pretty situational thing, it's sometimes harder and sometimes easier to judge cases. 

Outside judgement for a single/governing individual is pretty tough so I'd rather raise complaints directly with given admins, but given the status of federation that probably proves harder if things already went their way.

> Considering that, I take it to simply mean "we are not like them! (except when we are)" and appear as victims in a grand defederation scheme by "woke" people while doing the same.

That's to be applied to the instances in question, I guess. In general, I haven't been super active on the fediverse in the recent times so I don't know how heated exactly the deferation topic is, as compared to the time when I wrote this up initially.

I get your complaints on the matter though. In general, it'd mean I'd have to discuss the topic with the admins and approach them about "breach of the covenant" and I'm not sure what kind of results that would yield, if any. I'm not the final instance of power, in the end, I wouldn't be able to influence much.
