### ISSUE TITLE
Remove fedi.absturztau.be

### ISSUE THREAD

**Issue by M-i-k-o-t-o** [pixeldesu/fediverse-friendly-moderation-covenant#9]
See https://fedi.absturztau.be/notice/A8ikH8RP0VJfIPSF2O

This breaks "Communication before Actions" and "No Guilt-by-Association/Federation" (the kiwifarms instance is being defederated for being associated with the kiwifarms forum).

In addition they are known for banning local users that break no rules of the instance. Breaking "Actions taken will respond to the bare minimum to keep the network operating and not influence the ability of the instances users to connect to other people".

**Comment by pixeldesu** [comment]
> Regardless of all given points above, in special cases the instance moderation/administration might still opt to block an instance, while this is tried to be avoided at most.

First of all, I'm not a governing instance nor authority on who follows the self-imposed rules or not.

It's specifically written to be left open too, because of cases like this, and when the moderation team of an instance decides to defederate/block an instance to keep its own users safe, then so be it.
